# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    description: Build dotnet services
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
    steps:
      - checkout
      - run:
          name: Build core service
          command: dotnet build --configuration Release src/StellarEmpire.Core.Service/StellarEmpire.Core.Service.csproj
      - run:
          name: Build game service
          command: dotnet build --configuration Release src/StellerEmpire.Game.Service/StellarEmpire.Game.Service.csproj

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  stellar-empire-workflow:
    jobs:
      - build
